import type { MetadataRoute } from "next";

const BASE_URL = "https://neothink.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  const routes = [
    { path: "", changeFrequency: "weekly" as const, priority: 1.0 },
    { path: "/unleashed", changeFrequency: "monthly" as const, priority: 0.9 },
    { path: "/neothink", changeFrequency: "monthly" as const, priority: 0.9 },
    { path: "/neovia", changeFrequency: "monthly" as const, priority: 0.9 },
    { path: "/immortalis", changeFrequency: "monthly" as const, priority: 0.82 },
    { path: "/about", changeFrequency: "monthly" as const, priority: 0.88 },
    { path: "/mark-hamilton", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/unified-field", changeFrequency: "monthly" as const, priority: 0.9 },
    { path: "/the-way", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/published-work", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/manuscripts", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/prime-law", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/get-involved", changeFrequency: "monthly" as const, priority: 0.75 },
    { path: "/free-courses", changeFrequency: "monthly" as const, priority: 0.78 },
    { path: "/neothink-university", changeFrequency: "monthly" as const, priority: 0.77 },
    { path: "/neothink-reviews", changeFrequency: "monthly" as const, priority: 0.76 },
    { path: "/events", changeFrequency: "monthly" as const, priority: 0.77 },
    { path: "/programs", changeFrequency: "monthly" as const, priority: 0.74 },
    { path: "/project-life", changeFrequency: "monthly" as const, priority: 0.74 },
    { path: "/twelve-visions-party", changeFrequency: "monthly" as const, priority: 0.76 },
    { path: "/the-movement", changeFrequency: "monthly" as const, priority: 0.76 },
    {
      path: "/neothink-secret-society-differs-other-groups",
      changeFrequency: "monthly" as const,
      priority: 0.74,
    },
    {
      path: "/is-neothink-just-another-self-help-book",
      changeFrequency: "monthly" as const,
      priority: 0.72,
    },
    {
      path: "/neothink-society-empowering-challenging",
      changeFrequency: "monthly" as const,
      priority: 0.71,
    },
    {
      path: "/neothink-twelve-visions-party-truth",
      changeFrequency: "monthly" as const,
      priority: 0.71,
    },
    {
      path: "/discern-genuine-secret-society-opportunities",
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      path: "/secret-society-invitation-letter",
      changeFrequency: "monthly" as const,
      priority: 0.69,
    },
    {
      path: "/join-neothink-society-secret-meetings",
      changeFrequency: "monthly" as const,
      priority: 0.69,
    },
    {
      path: "/neothink-society-clearing-misunderstandings",
      changeFrequency: "monthly" as const,
      priority: 0.69,
    },
    {
      path: "/mark-hamiltons-neothink-surprising-logic",
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      path: "/truth-about-neothink-society",
      changeFrequency: "monthly" as const,
      priority: 0.71,
    },
    {
      path: "/is-neothink-society-legit",
      changeFrequency: "monthly" as const,
      priority: 0.71,
    },
    {
      path: "/neothink-movement-financial-independence",
      changeFrequency: "monthly" as const,
      priority: 0.71,
    },
    {
      path: "/what-people-get-wrong-neothink-university",
      changeFrequency: "monthly" as const,
      priority: 0.71,
    },
    {
      path: "/neothink-mastermind-group-success-stories",
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      path: "/freedom-key-to-unlocking-true-wealth",
      changeFrequency: "monthly" as const,
      priority: 0.72,
    },
    {
      path: "/reprogram-mind-to-be-rich",
      changeFrequency: "monthly" as const,
      priority: 0.72,
    },
    {
      path: "/how-to-raise-a-genius",
      changeFrequency: "monthly" as const,
      priority: 0.72,
    },
    { path: "/a-society-without-politics-poverty-or-war", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/aliens-real-never-visit-earth", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/are-we-the-illuminati-truth", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/escape-the-matrix-now", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/finding-achieving-your-life-purpose", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/how-to-be-a-leader-the-one-thing-holding-you-back", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/new-country-with-no-taxes", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/philosopher-make-your-life-exciting-again-do-this", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/sell-anything-marketing-secret", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/separating-heroes-from-dreamers", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/the-future-of-humanity-building-a-new-country-without-rulers", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/the-secret-to-a-wealthy-healthy-peaceful-country", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/think-like-elon-musk-mind-hacks", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/this-is-how-close-we-are-to-biological-immortality", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/trumps-victory-beginning-new-era", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/universal-wealth-secrets-the-solution-exposed", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/why-neothink-makes-you-irresistible", changeFrequency: "monthly" as const, priority: 0.72 },
    { path: "/youre-being-manipulated-they-use-guilt-to-control-you", changeFrequency: "monthly" as const, priority: 0.72 },
    {
      path: "/category/neothink-philosophy",
      changeFrequency: "weekly" as const,
      priority: 0.74,
    },
    {
      path: "/category/neothink-awakening",
      changeFrequency: "weekly" as const,
      priority: 0.74,
    },
    {
      path: "/category/neothink-concepts",
      changeFrequency: "weekly" as const,
      priority: 0.74,
    },
    {
      path: "/category/neothink-mentality",
      changeFrequency: "weekly" as const,
      priority: 0.74,
    },
    {
      path: "/mark-hamiltons-story",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/immortalis-the-great-experiment-of-our-time",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-city-that-cures-disease-neovia",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-missing-key-to-universal-prosperity",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-greatest-mental-breakthrough",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/a-knight-in-shining-armor-immortalis",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/land-based-immortalis",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/libertarians-next-big-possibility",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/mont-pelerin-pivot-into-our-essence",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-grand-experiment-of-our-time",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/breaking-the-chains-on-consciousness",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-unbreakable-equation",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/what-all-philosophies-get-wrong",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/how-neothink-brings-you-world-of-prosperity",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-cult-you-never-knew-existed",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/how-every-individual-can-be-wealthy",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/a-new-country-the-great-experiment-called-immortalis",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-beautiful-vs-the-ugly-in-our-world-3",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/how-jobs-will-change",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/decoding-super-puzzle",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/starting-our-own-country",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/live-longer",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-two-obstacles-to-curing-aging",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/spreading-immortalis-to-world-leaders",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/building-the-engine-behind-immortalis",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-job-revolution",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-2400-year-mistake",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/strategic-briefing-for-presidents",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/the-year-capitalism-sets-the-world-free",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/creating-the-demand-to-live-forever",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/illusion-pollution",
      changeFrequency: "monthly" as const,
      priority: 0.73,
    },
    {
      path: "/friday-night-essence",
      changeFrequency: "monthly" as const,
      priority: 0.74,
    },
    {
      path: "/self-leader-secret",
      changeFrequency: "monthly" as const,
      priority: 0.74,
    },
    {
      path: "/integrated-thinking",
      changeFrequency: "monthly" as const,
      priority: 0.74,
    },
    {
      path: "/value-creator",
      changeFrequency: "monthly" as const,
      priority: 0.74,
    },
    { path: "/neothink-mentality", changeFrequency: "monthly" as const, priority: 0.82 },
    { path: "/rise-from-rut", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/freedom-from-rights", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/beyond-tunnel-vision", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/impact-profits", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/higher-level-thinking", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/areas-of-profit", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/unlock-your-genius", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/the-prime-law-mentality", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/soaring-productivity", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/cure-to-aging", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/soar-beyond-peers", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/money-love-affair", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/keep-the-balance", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/power-of-calm", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/podcast", changeFrequency: "monthly" as const, priority: 0.75 },
    { path: "/contact", changeFrequency: "monthly" as const, priority: 0.8 },
    { path: "/faq", changeFrequency: "monthly" as const, priority: 0.79 },
    { path: "/privacy-policy", changeFrequency: "yearly" as const, priority: 0.3 },
    { path: "/terms-and-conditions", changeFrequency: "yearly" as const, priority: 0.3 },
    // Agency-era Uncategorized posts (source-faithful migration, pre-2025-12-01).
    // Priority 0.6 keeps them indexable but below cornerstone and authored series.
    { path: "/what-will-shape-future-of-humanity", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/doubts-about-neothink-society", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/neothink-debate-minimal-government", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/who-joins-secret-societies", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/secret-society-letters-selling-happiness", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/neothink-manuscripts-skepticism-to-success", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/what-do-secret-societies-do", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/ancient-formula-wealth-influence-neothink", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/neothink-unrealistic-too-good-to-be-true", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/neothink-society-path-to-wealth", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/neothink-books-reveal-secret-world", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/are-secret-societies-really-secret", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/what-is-the-neothink-society", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/benefits-active-neothink-member", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/feeling-stuck-in-life-how-to-fix", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/what-is-the-purpose-of-life", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/not-passionate-about-anything", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/starting-over-at-50", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/make-money-stay-at-home-mom-2025", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/find-your-passion-life-career", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/deal-with-financial-stress", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/break-bad-habits-transformation-tips", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/finding-purpose-retirement", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/find-happiness-in-retirement", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/neothink-society-why-people-cant-stop-talking", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/neothink-21st-century-navigate-challenges", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/mark-hamilton-visionary-neothink", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/excel-at-work-33-practical-tips", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/how-to-have-fun-as-adult", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/good-financial-habits-change-life", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/self-leadership-strategies-empower-yourself", changeFrequency: "monthly" as const, priority: 0.6 },
    { path: "/create-maintain-healthy-mindset", changeFrequency: "monthly" as const, priority: 0.6 },
  ];

  return routes.map((route) => ({
    url: `${BASE_URL}${route.path}`,
    lastModified,
    changeFrequency: route.changeFrequency,
    priority: route.priority,
    alternates: {
      languages: {
        "en-US": `${BASE_URL}${route.path}`,
      },
    },
  }));
}
