/**
 * FAQ for `a-society-without-politics-poverty-or-war` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const SWPPW_FAQ = [
  {
    question: "What is a society without politics?",
    answer:
      "A business civilization based on the Prime Law—no ruling class, no political class, no initiatory force. Everything operates through mutual value exchange. With 100 billion people who have walked the earth, every civilization has had a political structure with rulers. This would be the first without one.",
  },
  {
    question: "How can there be order without government?",
    answer:
      "Beautiful order emerges naturally when no one can force or suppress anyone for their own glory and power. The Prime Law ensures all interactions are voluntary. Everyone contributes to society and benefits from geniuses who are no longer held back. Order comes from cooperation and aligned incentives, not coercion.",
  },
  {
    question: "Why would poverty disappear?",
    answer:
      "When geniuses of society are no longer held down by regulations and suppression, progress accelerates dramatically. Costs drop toward zero while values rise toward infinity. Poverty exists because suppression prevents the natural abundance that freed human creativity produces.",
  },
  {
    question: "Why would war disappear?",
    answer:
      "Wars exist because ruling classes use initiatory force to expand power and extract resources. In a business civilization with no ruling class and no initiatory force, there’s no mechanism for war. No one can force others into conflict. Peace is the natural state when all exchanges are voluntary.",
  },
  {
    question: "What is the Prime Law?",
    answer:
      "A constitution that eliminates all initiatory force. No person, group, or government can force anyone to do anything. Only self-defense is permitted. This single law creates the conditions for mutual value exchange to replace political coercion.",
  },
  {
    question: "What is the path to this society?",
    answer:
      "Start with a network state—a digital community operating under the Prime Law. Grow the community through mutual value exchange. Eventually acquire physical territory and achieve sovereignty as a nation state. This allows building the new paradigm without fighting the old political systems.",
  },
  {
    question: "Isn’t this just idealistic dreaming?",
    answer:
      "Every paradigm shift seemed impossible before it happened. The difference is that this approach doesn’t require convincing existing power structures to change. It simply builds an alternative. As prosperity flourishes in the new civilization, the model speaks for itself.",
  },
] as const;
