/**
 * Neothink Awakening article from WordPress post `a-society-without-politics-poverty-or-war` (id 5462).
 * Auto-generated by `scripts/generate-awakening-data.mjs`. Hand-tune intro wording,
 * quick-answer body, and related links after generation.
 *
 * @see https://neothink.com/wp-json/wp/v2/posts/5462
 */
import type { AwakeningArticleImage } from "@/components/neothink-awakening/neothink-awakening-article";

export const SWPPW_PATH = "/a-society-without-politics-poverty-or-war" as const;

export const SWPPW_IMAGE: AwakeningArticleImage = {
  src: "/images/wp/2026/01/A-Society-Without-Politics-Poverty-or-War.jpg",
  alt: "A Society Without Politics, Poverty, or War — Neothink Awakening article",
  width: 640,
  height: 480,
};

export const SWPPW_DATES = {
  datePublished: "2026-02-11",
  dateModified: "2026-02-12",
} as const;

export const SWPPW_META_TITLE = "A Society Without Politics, Poverty, or War" as const;

export const SWPPW_HEADLINE = "A Society Without Politics, Poverty, or War" as const;

export const SWPPW_YOUTUBE_ID = "kPq3Qx2Xtng" as const;

export const SWPPW_MIN_READ = "10 min read" as const;

export const SWPPW_INTRO_PARAS: readonly string[] = [
  "Mark Hamilton reveals how a business civilization based on the Prime Law eliminates politics, poverty, and war through mutual value exchange. This isn’t about choosing better politicians—it’s about recognizing that the political paradigm itself is the source of humanity’s suffering.",
];

export const SWPPW_QUICK_ANSWER_KICKER = "Quick answer" as const;
export const SWPPW_QUICK_ANSWER_TITLE = "What Is a Society Without Politics, Poverty, or War?" as const;
export const SWPPW_QUICK_ANSWER_LEAD_STRONG: string | undefined = undefined;

/** Prose body of the quick answer (first paragraph from WP). Edit by hand to add inline Links. */
export const SWPPW_QUICK_ANSWER_REST = "A business civilization based on the Prime Law—no ruling class, no political class, no initiatory force. Everything operates through mutual value exchange. When no one can force or suppress others, prosperity explodes, diseases get cured rapidly, poverty disappears, and peace becomes the natural state. This has never happened in human history." as const;
