/**
 * FAQ for `aliens-real-never-visit-earth` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const ARNV_FAQ = [
  {
    question: "Do aliens exist?",
    answer:
      "Yes, conscious beings almost certainly exist throughout the universe. When you understand numbers and the countless energy systems throughout the universe, it becomes clear that conscious life exists all over: civilizations may be light years apart, but they’re there. This has become more accepted since the work of Carl Sagan and others.",
  },
  {
    question: "Have aliens ever visited Earth?",
    answer:
      "No. Any civilization advanced enough to travel millions of light years through space would have nothing to gain from visiting Earth. They would be so far beyond us technologically that we would be like kindergarten to them. The sheer cost in time, energy, and resources would never be worth it for beings who could learn nothing from us.",
  },
  {
    question: "What is the Nuclear Decision Threshold?",
    answer:
      "The Nuclear Decision Threshold is the point when conscious beings develop enough power and energy to wipe out civilization on their planet. To advance beyond this threshold, a civilization must purge irrationality and mysticism. Earth is currently right at this threshold. Civilizations that survive it enter an era of pure rationality and rapid technological advancement.",
  },
  {
    question: "Why wouldn’t advanced aliens want to help or teach us?",
    answer:
      "The sheer cost in time, energy, and resources to travel light years would not be worth it. Advanced beings would find much more productive ways to teach more advanced conscious beings for greater return. It’s like asking why a busy adult wouldn’t fly around the world to teach a kindergarten class for a week: they simply wouldn’t.",
  },
  {
    question: "What is the Universal Computer theory?",
    answer:
      "Mark Hamilton proposes that a Universal Computer exists throughout the universe where all conscious civilizations pour their knowledge and can tap into shared information. Humanity cannot access it yet, but if we get past our Nuclear Decision Threshold and continue moving in a rational direction, we will ultimately reach that point.",
  },
  {
    question: "How long have humans been truly conscious?",
    answer:
      "Only about 3,000 years. Studies and historical writings: including the Bible: demonstrate this transition from a more animal-like mind that automatically reacted to stimuli, to the conscious mind with introspection and decision-making ability. We have only recently entered the exponential phase of advancement with AI technology.",
  },
] as const;
