/**
 * Neothink Awakening article from WordPress post `are-we-the-illuminati-truth` (id 5246).
 * Auto-generated by `scripts/generate-awakening-data.mjs`. Hand-tune intro wording,
 * quick-answer body, and related links after generation.
 *
 * @see https://neothink.com/wp-json/wp/v2/posts/5246
 */
import type { AwakeningArticleImage } from "@/components/neothink-awakening/neothink-awakening-article";

export const AWTI_PATH = "/are-we-the-illuminati-truth" as const;

export const AWTI_IMAGE: AwakeningArticleImage = {
  src: "/images/wp/2026/01/Are-We-the-Illuminati-The-Truth-Behind-the-Allegations.jpg",
  alt: "Are We the Illuminati? The Truth Behind the Allegations, Neothink Awakening article",
  width: 1280,
  height: 720,
};

export const AWTI_DATES = {
  datePublished: "2026-01-24",
  dateModified: "2026-02-11",
} as const;

export const AWTI_META_TITLE = "Are We the Illuminati? The Truth Behind the Allegations – Mark Hamilton Explains" as const;

export const AWTI_HEADLINE = "Are We the Illuminati? The Truth Behind the Allegations" as const;

export const AWTI_YOUTUBE_ID = "l79YZkjgxmo" as const;

export const AWTI_MIN_READ = "11 min read" as const;

export const AWTI_INTRO_PARAS: readonly string[] = [
  "For five decades, the private Neothink Club has been called “the new Illuminati.” Mark Hamilton, its founder, has remained largely silent about this label: until now.",
  "In a recent discussion, Hamilton addressed the allegation directly. His response wasn’t defensive or dismissive. Instead, he did something unexpected: he acknowledged the parallels.",
];

export const AWTI_QUICK_ANSWER_KICKER = "Quick answer" as const;
export const AWTI_QUICK_ANSWER_TITLE = "Is Neothink the Illuminati?" as const;
export const AWTI_QUICK_ANSWER_LEAD_STRONG = "Neothink has been called “the new Illuminati” for over 50 years" as const;

/** Prose body of the quick answer (first paragraph from WP). Edit by hand to add inline Links. */
export const AWTI_QUICK_ANSWER_REST = "due to striking parallels with the original Bavarian Illuminati: both operated as secret societies, both opposed ruling class control over society, both faced government persecution, and both influenced world events from behind the scenes. However, unlike conspiracy theories suggest, Neothink is entirely benevolent: focused on achieving pure freedom and helping humanity thrive through the elimination of initiatory force." as const;
