/**
 * FAQ for `escape-the-matrix-now` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const EMN_FAQ = [
  {
    question: "What is the Neothink Awakening?",
    answer:
      "The Neothink Awakening is the psychological, physical, and conscious shift that occurs as someone breaks into the Neothink Mentality: the next evolution of the human mind. It involves moving from following mode to creative mode: integrating reality and creating values.",
  },
  {
    question: "What is following mode vs creative mode?",
    answer:
      "Following mode is the residual bicameral mentality where people follow external authorities, stay in routine ruts, and never use their creative minds. Creative mode is how humans are meant to live: integrating reality, becoming entrepreneurs, creating values, and experiencing genuine purpose.",
  },
  {
    question: "What is the maze of illusions?",
    answer:
      "The maze is the system of illusions crafted by the ruling class to keep people trapped in following mode. The walls are too high to see anything outside, so people live their little lives, feeling like there should be more, but never finding it.",
  },
  {
    question: "Who are the intellectually beautiful vs intellectually ugly?",
    answer:
      "The intellectually beautiful are value creators who bring genuine value to the world through innovation and entrepreneurship. The intellectually ugly are those who rise by suppressing value creators: politicians, regulatory bureaucrats, and others who create illusions to maintain power.",
  },
  {
    question: "What is the bicameral mind?",
    answer:
      "The bicameral mind was humanity’s pre-conscious state about 3,000 years ago, where the brain didn’t integrate or introspect. People operated in automatic reactive mode, following audio hallucinations they perceived as gods. Residual following-mode tendencies remain.",
  },
  {
    question: "What is the Nuclear Decision Threshold?",
    answer:
      "A concept developed by Dr. Frank R. Wallace describing the point where a civilization has the power to destroy itself. To survive, it must eliminate irrationality. Those that pass through become purely rational civilizations: the Civilization of the Universe.",
  },
  {
    question: "Why is Mark Hamilton going public now after 45+ years?",
    answer:
      "Hamilton sees the world deteriorating rapidly and approaching the nuclear decision threshold. His priority is the future of children and grandchildren. After decades of private clubs with 2 million members, he’s launching a public movement to build a value creation civilization.",
  },
] as const;
