/**
 * Neothink Awakening article from WordPress post `new-country-with-no-taxes` (id 5361).
 * Auto-generated by `scripts/generate-awakening-data.mjs`. Hand-tune intro wording,
 * quick-answer body, and related links after generation.
 *
 * @see https://neothink.com/wp-json/wp/v2/posts/5361
 */
import type { AwakeningArticleImage } from "@/components/neothink-awakening/neothink-awakening-article";

export const NCNT_PATH = "/new-country-with-no-taxes" as const;

export const NCNT_IMAGE: AwakeningArticleImage = {
  src: "/images/wp/2026/02/A-New-Country-with-No-Taxes-Mark-Hamilton.jpg",
  alt: "A New Country with No Taxes? — Neothink Awakening article",
  width: 1280,
  height: 720,
};

export const NCNT_DATES = {
  datePublished: "2026-02-03",
  dateModified: "2026-02-11",
} as const;

export const NCNT_META_TITLE = "A New Country with No Taxes?" as const;

export const NCNT_HEADLINE = "A New Country with No Taxes?" as const;

export const NCNT_YOUTUBE_ID = "-QCpkJ9T_Ns" as const;

export const NCNT_MIN_READ = "10 min read" as const;

export const NCNT_INTRO_PARAS: readonly string[] = [
  "Mark Hamilton poses a revolutionary thought experiment: what if a country existed with no taxes, no burdensome regulations, and no initiatory force? What would happen when businesses, innovators, and hardworking people flood to this new society?",
];

export const NCNT_QUICK_ANSWER_KICKER = "Quick answer" as const;
export const NCNT_QUICK_ANSWER_TITLE = "How Can a Country Function Without Taxes?" as const;
export const NCNT_QUICK_ANSWER_LEAD_STRONG = "A country with no taxes is possible" as const;

/** Prose body of the quick answer (first paragraph from WP). Edit by hand to add inline Links. */
export const NCNT_QUICK_ANSWER_REST = "through voluntary tithing to competing service providers instead of forced taxation. Combined with no burdensome regulations and the Prime Law that bans initiatory force, this creates a society where everyone can live like multi-millionaires, disease is cured rapidly, and crime virtually disappears." as const;
