/**
 * Neothink Awakening article from WordPress post `philosopher-make-your-life-exciting-again-do-this` (id 5474).
 * Auto-generated by `scripts/generate-awakening-data.mjs`. Hand-tune intro wording,
 * quick-answer body, and related links after generation.
 *
 * @see https://neothink.com/wp-json/wp/v2/posts/5474
 */
import type { AwakeningArticleImage } from "@/components/neothink-awakening/neothink-awakening-article";

export const PMLEA_PATH = "/philosopher-make-your-life-exciting-again-do-this" as const;

export const PMLEA_IMAGE: AwakeningArticleImage = {
  src: "https://neothink.com/wp-content/uploads/2026/01/PHILOSOPHER-Make-Your-Life-Exciting-Again-DO-THIS.jpg",
  alt: "Make Your Life Exciting Again: Find Your Friday Night Essence — Neothink Awakening article",
  width: 1280,
  height: 720,
};

export const PMLEA_DATES = {
  datePublished: "2026-02-12",
  dateModified: "2026-02-12",
} as const;

export const PMLEA_META_TITLE = "PHILOSOPHER: Make Your Life Exciting Again – DO THIS" as const;

export const PMLEA_HEADLINE = "Make Your Life Exciting Again: Find Your Friday Night Essence" as const;

export const PMLEA_YOUTUBE_ID = "4fClCSLkZlM" as const;

export const PMLEA_MIN_READ = "20 min read" as const;

export const PMLEA_INTRO_PARAS: readonly string[] = [
  "Mark Hamilton reveals the practical technique to escape your stagnant rut and live your life’s ambition. Discover your Friday Night Essence and use the Mini Day schedule to transform what you love into your livelihood—not motivation that fades in two weeks, but a system that has transformed lives for 45 years.",
];

export const PMLEA_QUICK_ANSWER_KICKER = "Quick answer" as const;
export const PMLEA_QUICK_ANSWER_TITLE = "How Do You Make Your Life Exciting Again?" as const;
export const PMLEA_QUICK_ANSWER_LEAD_STRONG: string | undefined = undefined;

/** Prose body of the quick answer (first paragraph from WP). Edit by hand to add inline Links. */
export const PMLEA_QUICK_ANSWER_REST = "Discover your Friday Night Essence—something productive you love doing during “shutdown time.” Then use the Mini Day schedule to build it around your current job until it becomes your livelihood. This isn’t another “follow your passion” speech. It’s a practical system that transforms the impractical into reality, like Jack London rising from illiterate dock worker to legendary author." as const;
