/**
 * FAQ for `philosopher-make-your-life-exciting-again-do-this` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const PMLEA_FAQ = [
  {
    question: "What is the Friday Night Essence?",
    answer:
      "Your Friday Night Essence is something productive you do during “shutdown and tune-out” time: like a Friday night when you could be watching movies or going out. If you find yourself doing something productive that you love during this time, that’s your right brain delivering a message: this is who I am, this is what I want to do.",
  },
  {
    question: "What is the Mini Day schedule?",
    answer:
      "The Mini Day breaks tasks into physical movements with strict time blocks, creating constant deadline pressure like cramming for exams. Based on the assembly line concept, it’s the greatest productivity technique ever invented. Mark Hamilton gained 8-fold productivity overnight using this method: the equivalent of 64 hours in an 8-hour day.",
  },
  {
    question: "What is downstream focus?",
    answer:
      "Downstream focus is when you’re working on your Friday Night Essence and the difficulty feels easy: like swimming downstream. You glide past competitors who are struggling upstream in fields they don’t love. This is the key to competitive advantage. Without it, someone will swim right past you.",
  },
  {
    question: "How do I listen to my right brain?",
    answer:
      "Each morning, before letting anything clutter your mind, stay in that half-awake state. Don’t think about business, family, or problems. Keep your left brain blank and pay attention to feelings that come your way. Think about projects or decisions without analyzing: just be aware. Messages will come through feelings.",
  },
  {
    question: "Why doesn’t “find what you love” work?",
    answer:
      "Because even if you find what you love, it usually seems impractical. You get inspired for a week or two, then it fades. It’s an upstream battle. The dream goes back in the impractical section. What’s missing is the practical system: the Mini Day schedule that lets you actually pursue it around your current job.",
  },
  {
    question: "Why do people get stuck in routine ruts?",
    answer:
      "The following mode. From birth, we learn through mimicking: parents, siblings, authorities. We never break free into independent thinking. The ruling class suppresses us into cookie-cutter lives. Over time, “falling leaves of resignation” cover up our Friday Night Essence until we can’t even see it anymore.",
  },
  {
    question: "Does this apply to everyone regardless of circumstances?",
    answer:
      "Yes. Whether you’re in the projects or born wealthy, happiness comes from finding what you love and creating values. Jack London rose from illiterate poverty to literary greatness. Rich families have children suffering from depression. This system applies to everyone at their level because everyone has emotions that respond to value creation.",
  },
] as const;
