/**
 * FAQ for `sell-anything-marketing-secret` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const SAMS_FAQ = [
  {
    question: "What are forces of nature in marketing?",
    answer:
      "Forces of nature are primal drives rooted in survival pressures—sex (propagation), instant gratification (maximum calories for minimum effort), popularity (tribal acceptance), and attention (survival advantage). These represent the largest common denominator needs and are coded into human DNA from hunter-gatherer days.",
  },
  {
    question: "What is the Child of the Past marketing technique?",
    answer:
      "The Child of the Past is Mark Hamilton’s secret marketing technique that generated $350 million in sales. It involves reawakening the sense of wonder, excitement, and expectation people had in their youth—before adult life caused them to resign their dreams. This is the largest common denominator need on Earth.",
  },
  {
    question: "What’s the difference between pain points and forces of nature?",
    answer:
      "Pain points are specific problems customers want solved. Forces of nature are deeper—primal survival drives coded in DNA. Pain points work, but forces of nature are more powerful because they tap into biological imperatives. The most successful marketers understand both levels.",
  },
  {
    question: "Why does “sex sell” in marketing?",
    answer:
      "Sex sells because propagation of the species is a force of nature—a biological imperative for survival. It’s coded into human DNA. Similarly, “get rich quick” appeals work because humans are wired to get maximum caloric intake (resources) with minimum effort—another survival adaptation.",
  },
  {
    question: "How did Mark Hamilton sell over $350 million in books?",
    answer:
      "Hamilton sold over 3 million books at an average price of $150 each by finding “searchers”—people whose Child of the Past was still alive—and sending personal invitation letters to his private Neothink Club. His technique of awakening dormant dreams and expectations drove unprecedented response rates.",
  },
  {
    question: "Who are the “searchers” in marketing?",
    answer:
      "Searchers are people who still feel there’s something more to life than what they’re experiencing. Their Child of the Past—that sense of wonder and expectation from youth—is still breathing inside them, even if resigned. These are the ideal prospects because they’re receptive to having those dormant dreams reawakened.",
  },
  {
    question: "What makes ethical marketing different from manipulation?",
    answer:
      "Ethical marketing appeals to genuine needs and delivers real value. Hamilton emphasizes that every product must be backed by a full refund policy—this removes questions of legitimacy. Your product must deliver actual value to match your marketing promises, otherwise it’s fraud and you’ll go bankrupt from refunds.",
  },
] as const;
