/**
 * FAQ for `the-secret-to-a-wealthy-healthy-peaceful-country` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const SWHPC_FAQ = [
  {
    question: "What is a pure business civilization?",
    answer:
      "A civilization with no ruling classes, operating solely on mutual value exchange under the Prime Law. There is no initiatory force, no fraud, no suppression. Free geniuses and advancing technology drive prices toward zero and values toward infinity. Hamilton equates this to the Civilization of the Universe, what civilizations across the universe achieve after surviving their nuclear decision threshold.",
  },
  {
    question: "What is the Neothink Network State?",
    answer:
      "A digital country under the Prime Law that Hamilton is establishing as the first living example of a pure business civilization. Unlike transitioning an existing political nation, the Network State starts immediately in its purest form. Citizens can join, do business, and experience the business civilization without waiting for political systems to evolve.",
  },
  {
    question: "What does “stimulate first, educate later” mean?",
    answer:
      "Hamilton’s approach to reaching the masses. Instead of leading with explanations (which loses people), you lead with bold, stimulating claims, end poverty, cure disease, eliminate crime. When people ask “How?” you’ve hooked them and earned permission to educate. Stimulation makes the world go round; education follows.",
  },
  {
    question: "How would a business civilization cure poverty?",
    answer:
      "In a business civilization, the free geniuses of society are no longer hampered by force-backed regulations. Their rapidly advancing technology drives prices toward zero and values toward infinity. Hamilton argues that cost-prohibitive regulations at every turn prevent the dynamics needed for major advancements in medicine, industry, and quality of life.",
  },
  {
    question: "What was the billionaire project?",
    answer:
      "Hamilton ran targeted Google ads to billionaires who have invested heavily in living forever, including Brian Johnson, Peter Thiel, and others. The ads appeared as information nuggets on their search engine results and linked to personalized letters on cure2aging.com. Brian Johnson subsequently announced his goal to start a new country. Google later canceled all of Hamilton’s ads, ending the project.",
  },
  {
    question: "What does “emotional withdrawal” mean in this context?",
    answer:
      "Instead of fighting the political system directly, Hamilton advocates pulling back emotionally and intellectually from the ruling class structure. This withdrawal brings immediate personal power, changes you forever, and spreads naturally to others. Combined with joining the Neothink Network State, it creates a growing movement that the ruling class cannot stop.",
  },
] as const;
