/**
 * FAQ for `the-future-of-humanity-building-a-new-country-without-rulers` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const FHBNCWR_FAQ = [
  {
    question: "What is the Prime Law?",
    answer:
      "The Prime Law is the most fundamental natural law of protection. It states that no person, group, or government can initiate force upon others. One person can do whatever they want with themselves and their property, as long as it doesn’t harm another individual or their property. Only self-defense force is moral.",
  },
  {
    question: "What is initiatory force?",
    answer:
      "Initiatory force is the actual initiation of force on others. It includes regulations, executive orders, and legislation that require compliance under threat of civil penalties or criminal punishment. It’s the “rule of man”: policies enforced simply because those in power prefer them, not because they serve the people.",
  },
  {
    question: "What is a business civilization?",
    answer:
      "A business civilization operates entirely on mutual value exchange with no ruling class and no initiatory force. Every business succeeds only by creating genuine value for people. Unlike political civilizations where some benefit from suppressing others, business civilizations reward only value creation.",
  },
  {
    question: "Why is this different from left vs right politics?",
    answer:
      "This isn’t a point on the political spectrum from left to right: it’s a third dimension entirely. Instead of choosing between political factions that all use initiatory force, this approach says “no” to politics altogether. It’s the anti-politics option that has never been available before.",
  },
  {
    question: "What are the three benefits of the new country?",
    answer:
      "Wealth: Everyone lives like millionaires as costs drop toward zero while values soar toward infinity. Health: Without regulatory suppression, geniuses can cure fatal diseases rapidly. Peace: Crime becomes irrational when everyone is wealthy and the punishment for violating the Prime Law is severe.",
  },
  {
    question: "What is a network state?",
    answer:
      "A network state is a country that begins digitally with citizens across the world, then manifests into physical land and territory. Based on Balaji Srinivasan’s concept, it allows starting fresh rather than trying to reform existing political systems. The Neothink network state will eventually seek physical sovereignty.",
  },
  {
    question: "What is the timeline for this new country?",
    answer:
      "Mark Hamilton has outlined a 10-year plan: Start with a digital network state and build community, grow through crowdsourcing and raise funds, purchase land, and work toward establishing sovereignty. The ultimate goal is creating a civilization based on the Prime Law where fatal diseases and aging itself can be cured.",
  },
] as const;
