/**
 * FAQ for `this-is-how-close-we-are-to-biological-immortality` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const HCBI_FAQ = [
  {
    question: "What is Project Life?",
    answer:
      "Project Life is Mark Hamilton’s 45-year initiative to cure aging and death. It encompasses three legs: freeing individuals from stagnation into creative mode, eliminating ruling class suppression through the Prime Law, and establishing a new civilization where geniuses can freely advance medical research.",
  },
  {
    question: "What is biological immortality?",
    answer:
      "Biological immortality (also called longevity escape velocity) is the point where medical technology advances fast enough that for every year you live, science can extend your life by one year or more: effectively eliminating aging as a cause of death.",
  },
  {
    question: "Why don’t most people want to live forever?",
    answer:
      "Most people are stuck in “following mode”: living stagnant lives with only occasional moments of happiness. Like static between songs on a vinyl record, stagnation makes life feel like a burden rather than a gift. Only those in “creative mode” experience the continuous exhilaration that makes eternal life desirable.",
  },
  {
    question: "What is the Prime Law?",
    answer:
      "The Prime Law is a constitutional principle that banishes all initiatory force from government and civilization. It states that no person or group may initiate force against another: only self-defense force is permitted. This natural law of protection enables the conditions for true progress.",
  },
  {
    question: "How do regulations suppress medical progress?",
    answer:
      "Government regulations backed by force create a “spider web” that catches geniuses, scientists, and researchers trying to advance medical breakthroughs. These regulations are disguised as necessary supervision but actually serve to maintain power and control while retarding progress.",
  },
  {
    question: "What is the Great Technological Revolution?",
    answer:
      "The Great Technological Revolution is what happens when geniuses are freed from regulatory suppression. Values soar toward infinity while costs are driven toward zero: enabling everyone to live like multimillionaires. Computing provides a small example: room-sized mainframes are now pocket calculators.",
  },
  {
    question: "How close are we to curing aging?",
    answer:
      "Hamilton estimates 20 years: 10 years to establish a sovereign territory based on the Prime Law, then 10 more years for unrestricted medical research to cure fatal diseases and aging itself. This generation may be the first to achieve biological immortality.",
  },
] as const;
