/**
 * Neothink Awakening article from WordPress post `this-is-how-close-we-are-to-biological-immortality` (id 5435).
 * Auto-generated by `scripts/generate-awakening-data.mjs`. Hand-tune intro wording,
 * quick-answer body, and related links after generation.
 *
 * @see https://neothink.com/wp-json/wp/v2/posts/5435
 */
import type { AwakeningArticleImage } from "@/components/neothink-awakening/neothink-awakening-article";

export const HCBI_PATH = "/this-is-how-close-we-are-to-biological-immortality" as const;

export const HCBI_IMAGE: AwakeningArticleImage = {
  src: "/images/wp/2026/01/This-is-How-Close-We-Are-to-Biological-Immortality.jpg",
  alt: "This is How Close We Are to Biological Immortality, Neothink Awakening article",
  width: 1280,
  height: 720,
};

export const HCBI_DATES = {
  datePublished: "2026-02-09",
  dateModified: "2026-02-11",
} as const;

export const HCBI_META_TITLE = "This is How Close We Are to Biological Immortality" as const;

export const HCBI_HEADLINE = "This is How Close We Are to Biological Immortality" as const;

export const HCBI_YOUTUBE_ID = "bL_DWdm7hgA" as const;

export const HCBI_MIN_READ = "14 min read" as const;

export const HCBI_INTRO_PARAS: readonly string[] = [
  "Mark Hamilton reveals Project Life: his 45-year journey toward curing aging and death. This isn’t wishful thinking. It’s a three-leg approach that addresses the psychological, political, and medical barriers standing between humanity and the end of aging.",
];

export const HCBI_QUICK_ANSWER_KICKER = "Quick answer" as const;
export const HCBI_QUICK_ANSWER_TITLE = "How Close Are We to Biological Immortality?" as const;
export const HCBI_QUICK_ANSWER_LEAD_STRONG: string | undefined = undefined;

/** Prose body of the quick answer (first paragraph from WP). Edit by hand to add inline Links. */
export const HCBI_QUICK_ANSWER_REST = "Mark Hamilton estimates 20 years: 10 years to establish a sovereign territory based on the Prime Law (freeing geniuses from regulatory suppression), then 10 more years of unrestricted medical research to cure fatal diseases and aging itself. This generation may be the first to achieve longevity escape velocity: where science advances faster than you age." as const;
