/**
 * FAQ for `trumps-victory-beginning-new-era` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const TVBNE_FAQ = [
  {
    question: "What is DOGE (Department of Government Efficiency)?",
    answer:
      "DOGE is a government efficiency initiative announced in late 2024, led by Elon Musk and Vivek Ramaswamy. Its stated goal is reducing federal spending by up to $2 trillion annually through eliminating wasteful bureaucracy and regulations. Mark Hamilton sees this as “Phase One” toward a freer society.",
  },
  {
    question: "How does reducing government size benefit ordinary people?",
    answer:
      "When government shrinks, people keep more money (less taxation), face fewer regulations on their businesses and lives, and benefit from increased economic productivity. Hamilton points to the computer revolution as proof—when government couldn’t regulate the industry, costs dropped 1,000-fold.",
  },
  {
    question: "What is Immortalis?",
    answer:
      "Immortalis is a new country founded by Mark Hamilton, currently operating as a digital network state with plans to acquire physical territory within 10 years. It operates under the Prime Law with no politicians, no bureaucratic regulations, and no forced taxation—only a voluntary 10% tithe for protection services.",
  },
  {
    question: "Why does Mark Hamilton call government a cult?",
    answer:
      "Hamilton defines a cult as controlling people’s lives through mind manipulation for the benefit of leaders. Government fits this definition: it controls citizens from childhood through education and regulations, manipulates through “illusion pollution” (propaganda and false promises), and enriches politicians who enter poor and leave wealthy.",
  },
  {
    question: "What is the Prime Law?",
    answer:
      "The Prime Law is the constitutional foundation of Immortalis that removes all initiatory force from government and society. It means no forced taxation, no regulatory coercion, and government limited strictly to protecting individual rights. Under the Prime Law, the smallest minority—the individual—is fully protected.",
  },
  {
    question: "How would a purely free economy affect healthcare?",
    answer:
      "Without FDA regulations and bureaucratic delays, medical research could advance at “computer revolution” speed. Hamilton argues a free territory would become the medical mecca of the world, attracting genius researchers to pursue cures for aging, cancer, and other diseases without government interference.",
  },
  {
    question: "Why would crime disappear in a free society?",
    answer:
      "Hamilton identifies three factors: (1) The primary cause of crime—need for money—disappears when everyone is wealthy, (2) With protection as government’s only purpose, justice becomes swift and certain, deterring potential criminals, and (3) Equal protection under the Prime Law eliminates the divisions that breed conflict.",
  },
] as const;
