/**
 * FAQ for `universal-wealth-secrets-the-solution-exposed` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const UWSSE_FAQ = [
  {
    question: "What is the following mode?",
    answer:
      "The following mode is a biological remnant passed down for 3,000 years since the bicameral civilization. As babies, we enter consciousness by mimicking our parents and older siblings. Most people never fully leave this following mode. Hamilton calls it the scourge of mankind — the root cause of the parasitical ruling class that has existed in every civilization in history.",
  },
  {
    question: "Why doesn’t fighting external authorities work?",
    answer:
      "Because it is their game, their wheelhouse, their rules. They have millennia-old skills — illusions, doublespeak, initiatory force. Going up against them actually gives them power by allowing them to resist you. The result is a cycle: one step forward, two steps backward. No civilization in the history of 100 billion people has ever freed itself this way.",
  },
  {
    question: "What does Hamilton mean by “the rocks are an illusion”?",
    answer:
      "The external authorities blocking our freedom — the rocks in the cave metaphor — are sustained by one illusion: that we need them, that they benefit us. Their power is unearned and depends entirely on our following mode. Remove the following mode and the need for them vanishes. The rocks were never real obstacles — they were an illusion that can be dissolved.",
  },
  {
    question: "What is the innocent quiz?",
    answer:
      "A series of casual questions you can ask friends and family to help them see their own following mode. Examples: Do you easily believe Google searches? Did you question authorities during the pandemic? Do you feel pressured to go with the social current? The key is to present it lightly, include yourself, and never lecture or challenge.",
  },
  {
    question: "Has pure capitalism ever existed?",
    answer:
      "No. Hamilton emphasizes that what people call capitalism has always been intertwined with political force. Big business and government have always been entangled. The bad reputation of capitalism comes from this entanglement, not from business itself. A pure business system under the Prime Law has never been experienced on Earth.",
  },
  {
    question: "How does reaching young parents break the chain?",
    answer:
      "Children grow up mimicking the world around them. If parents are in the following mode, their children flow into the following mode. But if parents break free into an integrating mode, their children see that instead and flow into integration naturally. This is how the 3,000-year chain from the bicameral civilization finally breaks — at its source.",
  },
] as const;
