/**
 * FAQ for `why-neothink-makes-you-irresistible` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const WNMYI_FAQ = [
  {
    question: "Is Neothink a dating community?",
    answer:
      "No, Neothink is not designed as a dating club. However, because the community is filled with people operating in creative mode with shared values, romantic connections naturally form more frequently than in typical groups.",
  },
  {
    question: "Why does intelligence matter for attraction?",
    answer:
      "Unlike other species that rely primarily on physical attributes, human survival historically depended on superior intelligence. We’re evolutionarily programmed to find higher-level thinkers attractive—it signals that potential offspring would have better survival chances.",
  },
  {
    question: "What is the difference between following mode and creative mode?",
    answer:
      "Following mode is being stuck in routine patterns, just doing assigned tasks, feeling stagnant. Creative mode is actively creating values, breaking through limitations, and experiencing genuine happiness because you’re functioning in harmony with your essence.",
  },
  {
    question: "Why are happy people more attractive?",
    answer:
      "Genuine happiness signals that someone is functioning well—operating in harmony with their nature. This authentic positive energy is inherently attractive because it suggests a healthy, thriving individual who would be a good partner.",
  },
  {
    question: "What is “value reflection” in relationships?",
    answer:
      "Value reflection is when two creative people share their happiness back and forth. You celebrate each other’s progress, support each other’s goals, and compound each other’s joy through shared creative experiences.",
  },
  {
    question: "Why do shared values matter for relationships?",
    answer:
      "Shared core values create instant common ground and eliminate many sources of conflict. When partners have similar worldviews and approaches to life, they can focus on growing together rather than negotiating fundamental differences.",
  },
  {
    question: "Should young people join Neothink specifically for relationships?",
    answer:
      "While Neothink isn’t a dating service, Hamilton encourages young adults to get involved because they’ll be surrounded by creative, value-driven people—significantly increasing the odds of finding a compatible life partner.",
  },
] as const;
