/**
 * FAQ for `youre-being-manipulated-they-use-guilt-to-control-you` (Neothink Awakening). Auto-generated by
 * `scripts/generate-awakening-data.mjs` from the Elementor FAQ block. Hand-tune
 * wording as needed.
 */
export const YBMG_FAQ = [
  {
    question: "How is guilt used as a weapon of control?",
    answer:
      "Guilt is weaponized by creating illusions that make innocent people feel responsible for things beyond their control. Those in power use facts out of context to establish “higher causes” that people feel obligated to support, regardless of how self-destructive compliance becomes.",
  },
  {
    question: "What is the difference between healthy guilt and manipulative guilt?",
    answer:
      "Healthy guilt results from your own actions that you recognize as wrong—it’s honest self-assessment that leads to growth. Manipulative guilt is imposed externally for things you didn’t do or can’t control, designed to make you compliant rather than help you improve.",
  },
  {
    question: "Why do innocent people accept guilt so easily?",
    answer:
      "Most people are value creators who want to be good and fit in with society. They don’t have the “dark matter” in their minds that manipulators possess, so they can’t conceive of someone deliberately using guilt as a weapon.",
  },
  {
    question: "How does pride serve as the antidote to guilt?",
    answer:
      "Pride comes from living in harmony with your true essence as a value creator. When you create genuine values for society, you build authentic self-esteem that makes external guilt manipulation ineffective.",
  },
  {
    question: "What is the difference between truth and fully integrated honesty?",
    answer:
      "Truth can be manipulated by presenting facts out of context. Fully integrated honesty requires pulling all relevant information together without omission or distortion. You can tell partial truths while being fundamentally dishonest.",
  },
  {
    question: "How can I protect myself from guilt manipulation?",
    answer:
      "When someone tries to instill guilt, immediately flag it mentally and refuse to let it enter your subconscious. Analyze it later: Is this about your actions or their control? Either dismiss manipulative guilt or take corrective action for genuine mistakes.",
  },
  {
    question: "Why does Hamilton say life is “unbearably short”?",
    answer:
      "Human consciousness is the most valuable thing in the known universe, yet we lose conscious beings in just 70-80 years. This perspective justifies the rightness of happiness—why waste your brief existence carrying imposed guilt?",
  },
] as const;
