/**
 * Neothink Awakening article from WordPress post `youre-being-manipulated-they-use-guilt-to-control-you` (id 5417).
 * Auto-generated by `scripts/generate-awakening-data.mjs`. Hand-tune intro wording,
 * quick-answer body, and related links after generation.
 *
 * @see https://neothink.com/wp-json/wp/v2/posts/5417
 */
import type { AwakeningArticleImage } from "@/components/neothink-awakening/neothink-awakening-article";

export const YBMG_PATH = "/youre-being-manipulated-they-use-guilt-to-control-you" as const;

export const YBMG_IMAGE: AwakeningArticleImage = {
  src: "https://neothink.com/wp-content/uploads/2026/01/Youre-Being-Manipulated-They-use-Guilt-to-Control-You.jpg",
  alt: "You’re Being Manipulated! They Use Guilt to Control You! — Neothink Awakening article",
  width: 1280,
  height: 720,
};

export const YBMG_DATES = {
  datePublished: "2026-02-07",
  dateModified: "2026-02-11",
} as const;

export const YBMG_META_TITLE = "You’re Being Manipulated! They use Guilt to Control You!" as const;

export const YBMG_HEADLINE = "You’re Being Manipulated! They Use Guilt to Control You!" as const;

export const YBMG_YOUTUBE_ID = "sC4GxlkV7QM" as const;

export const YBMG_MIN_READ = "12 min read" as const;

export const YBMG_INTRO_PARAS: readonly string[] = [
  "Mark Hamilton reveals how guilt is weaponized by those in power to control innocent people—and how you can break free. This isn’t about healthy self-assessment; it’s about the deliberate psychological manipulation that keeps value creators compliant and controllable.",
];

export const YBMG_QUICK_ANSWER_KICKER = "Quick answer" as const;
export const YBMG_QUICK_ANSWER_TITLE = "How Is Guilt Used to Control You?" as const;
export const YBMG_QUICK_ANSWER_LEAD_STRONG = "Guilt is a psychological weapon" as const;

/** Prose body of the quick answer (first paragraph from WP). Edit by hand to add inline Links. */
export const YBMG_QUICK_ANSWER_REST = "used by those in power to control you. Unlike physical force, guilt hijacks your natural desire to be good—making you comply with agendas that often harm your own interests. The antidote is pride built through genuine value creation, which makes you immune to external manipulation." as const;
